### ISSUE TITLE
Media sources not saving path for description, basePath or baseUrl

### ISSUE THREAD

**Issue by hcanning2014** [modxcms/revolution#12395]
Revo    2.3.3-pl
PHP Version 5.3.10-1ubuntu3.16
Mysql   5.5.41 
Apache 2.2
Media sources not saving path for description, basePath or baseUrl when creating new or by duplicating existing media sources and editing. Update Revo fro 2.3.x - 2.3.3

Issue on linode.com AND modxcloud.com with nginx ... btw -= cloned websites

**Comment by roele** [comment]
Can confirm the problem. Changing the values after creation resolves the issue.

**Comment by inreti** [comment]
Seems to be a caching issue. Observed this as well - if you hit save, then clear the cache and reload the page, it seems to work.

**Comment by matdave** [comment]
Ya, this is super annoying.  Create process clears the media source cache, but update and remove do not.

**Comment by Mark-H** [comment]
I can't reproduce, feel free to reopen if still an issue.

**Comment by inreti-sb** [comment]
Unfortunately still an (caching) issue in version 2.5.4. Please reopen. Thx!

**Comment by Jako** [comment]
Please add a some infomation to reproduce the issue.

**Comment by matdave** [comment]
I think maybe this got _(at least partially)_ resolved with the update to the Media Source listing process.  It was definitely an annoying issue in 2015, but I can't recreate this now in 2.5.4. @inreti-sb Are you seeing this on the media source, TVs, or where?

**Comment by inreti-sb** [comment]
On the media manager. E.g. if editing basePath, baseUrl, allowedFileTypes.
Just did some testing. It occures only on round about half of our MODX Revo instances (all 2.5.4).
Can't find  possible causes until now. On the same server one instance is affected, the other not.
Which further infos are helpful for you? I can offer a teamviewer session as well..

**Comment by pepebe** [comment]
It happens again on 2.6.5.

Media Source Grid. Double Click the title change the value tab to the next field. The change seems to be lost. Open the Media Source and you'll see your changes. Go back to the grid, the changes seem to be lost.

Media Source Settings. Double Click base_path. Change the value, tab to the next field. Hit save. Now reload the page. All changes are lost.

This happens at least 9 out of 10 times.

I've tried to change settings with browser cache on and off. If deleted core/cache a few times with no effect.

Again this happens on some instances and on others it doesn't happen at all.

**Comment by pepebe** [comment]
Update. If I duplicate a media source inside the grid, the changes I have done before are suddenly visible.

Experiment: 
Delete a media source. Nothing happens. 
Reload the media source grid. Still no change.
Duplicate the media source. The media source is gone.

**Comment by JoshuaLuckers** [comment]
> Media Source Grid. Double Click the title change the value tab to the next field. The change seems to be lost. Open the Media Source and you'll see your changes. Go back to the grid, the changes seem to be lost.

> Media Source Settings. Double Click base_path. Change the value, tab to the next field. Hit save. Now reload the page. All changes are lost.

I can not reproduce this behaviour. To help us better understand the issue:

- Is it possible to make a screen recording? 
- What browser (and version) or you using?
- Any error in the console of your browser?

**Comment by pepebe** [comment]
1. Sure, I'll prepare a screen recording
2. Chrome and FF on MacOS as well as Ubuntu
3. No errors. The connector.php seems to work

**Comment by alroniks** [comment]
I can not reproduce. And as I see other people too. I understand, that is an annoying bug and it difficult to catch it, but we, unfortunately, can afford to spend time to trying figure out what wrongs with it without a detailed error report.

Feel free to reopen, but for now, it will be closed as a quite old and inactive bug.
