### ISSUE TITLE
Configuration warning about core-dir

### ISSUE THREAD

**Issue by funkyduke** [modxcms/revolution#12565]
When upgrading to 2.4 I get a notification on the dashboard that the core-dir is accessible on the public web, but it's not! The .htaccess-file (inside the core-dir) is correct configurated.

**Comment by Mark-H** [comment]
What happens when you open core/docs/changelog.txt in the browser? What do you see?

**Comment by funkyduke** [comment]
then I see the changelog. Not good? What can I do more? I think some documentation would help because a lot will have the same and don't know what to do. Changing the ht.access to .htaccess inside the core-dir didn't help.

**Comment by inreti** [comment]
Thats exactly what the configcheck is for. so your .htaccess is _not_ configured correctly.
@Mark-H: what I said...

**Comment by funkyduke** [comment]
I got 'Deny from all' in it. Isn't that enough?

**Comment by bezumkin** [comment]
Are you sure that your server is using Apache2? .htaccess is working only in Apache2.

Maybe you need to configure Nginx?
```
location ~* ^/core/ {
    deny                all;
}
```

**Comment by funkyduke** [comment]
Sorry for my late reply: it's indeed Apache 2.

**Comment by OptimusCrime** [comment]
What version of Apache are you running? 2.2.x? 2.4.x?

**Comment by funkyduke** [comment]
@OptimusCrime: don't know. Does this make a difference for this issue?

**Comment by Pfeifakopf** [comment]
Same warning here. Apache/2.4.7 (Ubuntu), PHP 5.6, htaccess is fine, error 404 is shown at core/docs/changelog.txt

**Comment by inreti** [comment]
@funkyduke , @Pfeifakopf : what is in your .htaccess files?

**Comment by Mark-H** [comment]
@inreti I don't think that pull request made it into 2.4, it's still this in 2.4:

````
IndexIgnore */*
<Files *.php>
    Order Deny,Allow
    Deny from all
</Files>
````

**Comment by Mark-H** [comment]
Does look like the default wont help with the log file as it's limited to .php. Should probably get the updated ht.access into 2.4.1 then. The pull request for that is #12503.

**Comment by inreti** [comment]
@Mark-H you are right. It did not make it into 2.4.0 unfortunately... :-(

**Comment by mindeffects** [comment]
The link to the "changelog.txt" in the configcheck dashboard description is also wrong.
`http://modx.local/docs/changelog.txt` does not work.
It should be
`http://modx.local/core/docs/changelog.txt`
The `core/`is missing.

**Comment by inreti** [comment]
@mindeffects: wrong link fixed in #12571

**Comment by OptimusCrime** [comment]
Is this fixed then?

**Comment by inreti** [comment]
The wrong link is fixed and warnings when open_basedir in effect are supressed. The example ht.access is already fixed, but didn't make it into 2.4.0

**Comment by OptimusCrime** [comment]
Cool, guess we can close this then?

@modxbot close

**Comment by Mark-H** [comment]
The PR hasn't been merged yet, so let's keep it open until it's fixed in git ;)

**Comment by OptimusCrime** [comment]
Oh, I am so sorry @Mark-H.

Too fast on the trigger finger there.

**Comment by whitebyte** [comment]
BTW even after putting @inreti 's htaccess into the folder, warning still here. revo .2.4.0, apache 2.4.10

**Comment by inreti** [comment]
@whitebyte: can turn on log level to debug and see what is in the error log? And can you still access core/docs/changelog.txt with a browser.
=> the ht.access is just an example file. If it does not fit to your environment, you have to adjust it on your own. That's what the config check is intended for - it informs you that something is still wrong with your setup and your core folder is still accessible from outside.

**Comment by mindeffects** [comment]
Every Non-MODX-User I tell about this "core/ht.access" story just asks me:

ALL user is lazy, even pros.  Why don't you just let the setup rename "core/ht.access" into the "core/.htaccess" and done? Why the hassle with renaming manually? Find a nginx solution and let setup handle this as well.

Know what? I just cannot find any argument against their point. MODX 0, Others +1.

**Comment by juiceCake** [comment]
I agree with mindeffects. Make the proper .htaccess file default on install and let those users who want to take away that security measure or need to to change it for other reasons do so. Instead the mantra of MODX and flexibility is taken to an extreme, forcing many users to, after installing it, go in and take these extra steps. It takes time. Maybe not much, but if you're doing a bunch of installs/upgrades, the time adds up.

Instead the system puts out a warning that would be alarming to clients, telling you, effectively, that there is an issue with the install and you should go fix it manually, the installer won't bother setting something by default, which you can change if you like, that it highly recommends.

**Comment by inreti** [comment]
@whitebyte, @Pfeifakopf: does the configcheck widget still print out the warning at your site? if the .htaccess is valid and working it shouldn't show up. We need to find out what's wrong in your context in order to - maybe - fix the code.

**Comment by funkyduke** [comment]
Why isn't this fixed in 2.4.1? Any reason?

**Comment by rthrash** [comment]
@funkyduke a Pull Request was not submitted in time for the 2.4.1 release. Hopefully it will for 2.4.2. :)

**Comment by mindeffects** [comment]
It would be nice to know WHEN the doors are closing for a release!!!
Shouldn't be that hard. :-(

**Comment by rthrash** [comment]
@mindeffects patch releases are continual in nature and can be done frequently as important improvements are made or security holes are plugged. Minor releases definitely get more planning and target dates, but I don't think this has trickled down to patch-level releases yet.

**Comment by mindeffects** [comment]
Why not say:
"Wednesday, 23. Sept, 12:00 (noon) is the deadline for 2.4.1. All PRs after that date won't make it."

What is wrong with informing the community? 
What is wrong with planing (see below)?
What is wrong with knowing that things have to be ready until a certain date?
What is wrong with motivating people to get things out into daylight?

My own effort of getting one thing into 2.4.1 nows feel like a waste of time: I somehow read between the lines that 2.4.1 was coming and I dropped my current work and started to rush on the MODX PR. I had trouble with Git and didn't make it in time – but I never had a chance, because 2.4.1 was already locked up.
That's just frustrating! I should have spent the time on a (payed) project that is now over due!

This communication thing will never get better, will it?

P.S.: 5 months between 2.3.3 and 2.3.4
MODX Revolution 2.3.3-pl  (January 29, 2015)
MODX Revolution 2.3.4-pl  (June 23, 2015)

**Comment by Omeryl** [comment]
@mindeffects I understand your frustration, but perhaps this should be either brought to the community slack, the forums, or a new issue? It's flooding this issue with comments that are better elsewhere (my own personal opinion, I have no power or right to enforce it).

**Comment by mindeffects** [comment]
Thanks for your reply. :-)
Switching to Slack.

**Comment by Mark-H** [comment]
Closing per fix in #12503
